# Generated by Django 5.0 on 2023-12-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='assinado',
            field=models.BooleanField(default=False),
        ),
    ]
