# Generated by Django 5.0 on 2023-12-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_assinado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='assinado',
        ),
        migrations.AddField(
            model_name='documento',
            name='hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
